import {validatePublication} from './validate-publication.mjs';
import {readGalleryManifest} from './gallery-manifest.mjs';
import {editorialRevision} from './editorial-revision.mjs';
import {articleBody} from './galleries.mjs';
import fs from 'node:fs';
import path from 'node:path';
import {articles,categories,edition,candidates} from '../content.mjs';
const root=path.resolve(import.meta.dirname,'..'),base='https://tectonica.media';
validatePublication(articles,readGalleryManifest(),root);
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const json=o=>JSON.stringify(o).replaceAll('<','\\u003c');
const url=a=>'/articles/'+a.id+'/';
const dateLabel=d=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z')).replace(/ г\.$/,'');
const catKey=k=>k==='lighting'?'furniture':k;
const catName=k=>k==='lighting'||k==='furniture'?'Мебель и свет':k==='people'?'Люди':categories[k];
const nav=Object.entries(categories).filter(([k])=>k!=='lighting').map(([k,v])=>'<a href="/category/'+k+'/">'+catName(k)+'</a>').join('');
const img=(a,large=false)=>a.image?'<img src="/assets/images/'+a.image+'-'+(large?'1440':'640')+'.webp" srcset="/assets/images/'+a.image+'-640.webp 640w, /assets/images/'+a.image+'-1440.webp 1440w" sizes="'+(large?'(max-width: 700px) 100vw, 70vw':'(max-width: 700px) 100vw, 33vw')+'" width="1440" height="1080" alt="'+esc(a.imageAlt||a.title)+'" '+(large?'fetchpriority="high"':'loading="lazy"')+'>':'';
const meta=a=>'<div class="meta"><span>'+catName(a.category)+'</span><span>'+esc(a.place)+'</span></div>';
const card=(a,cls='')=>'<article class="card '+cls+'"><a href="'+url(a)+'">'+img(a)+(a.image&&!a.illustration?'<span class="photo-credit">'+esc(a.credit)+'</span>':'')+(a.illustration?'<span class="illustration-label">Иллюстрация TECTONICA</span>':'')+meta(a)+'<h3>'+esc(a.title)+'</h3><p>'+esc(a.dek)+'</p><span class="read">'+a.format+' ↗</span></a></article>';
const row=a=>'<article class="newsrow"><span class="rowcategory">'+catName(a.category)+'</span><a href="'+url(a)+'">'+(a.image?'<span class="row-illustration">'+img(a)+(a.illustration?'<small>Иллюстрация</small>':'')+'</span>':'')+'<h3>'+esc(a.title)+'</h3><p>'+esc(a.dek)+'</p></a><span class="arrow">↗</span></article>';
const section=(n,t,link,label='Все материалы')=>'<div class="sectionhead"><span class="sectionnumber">'+n+'</span><h2>'+t+'</h2>'+(link?'<a href="'+link+'">'+label+' ↗</a>':'')+'</div>';
const pages=[];
const credit=a=>a.image?'<span class="photo-credit">'+esc(a.credit)+'</span>':'';
const byId=id=>articles.find(a=>a.id===id);
const photoCard=(a,cls='')=>card(a,cls);
const heading=(title,desc,kicker='TECTONICA')=>'<div class="page-title"><span class="eyebrow">'+esc(kicker)+'</span><h1>'+esc(title)+'</h1><p>'+esc(desc)+'</p></div>';
const sourceLinks=a=>(a.sources||[{title:new URL(a.source).hostname.replace('www.',''),url:a.source}]).map(x=>'<a href="'+esc(x.url)+'" rel="noopener">'+esc(x.title)+' ↗</a>').join('');
const formats='<div class="formatnav" aria-label="Форматы"><a href="/daily/">За 15 минут ↗</a><a href="/feed/">Лента</a><a href="/features/">Разборы</a><a href="/radar/">Radar</a><a href="/archive/">Все материалы</a></div>';
const editorialList=ids=>ids.map(id=>byId(id)).filter(Boolean);
const currentIssuePath=path.join(root,'editorial/releases',edition+'.json');
const currentIssue=fs.existsSync(currentIssuePath)?JSON.parse(fs.readFileSync(currentIssuePath,'utf8')):{};
const selectionLabel=editorialRevision.picks.length+' '+(editorialRevision.picks.length===1?'история':editorialRevision.picks.length<5?'истории':'историй');
const issueClosing=(currentIssue.featurePitches?.length?section('ДАЛЬШЕ','Темы для большого материала',null)+'<div class="prose">'+currentIssue.featurePitches.map(p=>'<h3>'+esc(p.title)+'</h3><p>'+esc(p.text)+'</p><p><a href="/articles/'+esc(p.article)+'/">Отправная история ↗</a></p>').join('')+'</div>':'')+(currentIssue.radar?section('СИГНАЛ',currentIssue.radar.title,null)+'<div class="prose"><h3>'+esc(currentIssue.radar.subtitle)+'</h3><p>'+esc(currentIssue.radar.text)+'</p>'+currentIssue.radar.sources.map(s=>'<p><a href="'+esc(s.url)+'">'+esc(s.title)+' ↗</a></p>').join('')+'</div>':'');
const longreads=articles.filter(a=>a.format==='Разбор');
const radar=articles.filter(a=>a.format==='Radar');

function write(route,title,desc,body,article,options={}){
 const canonical=base+route; const og=article?.image?base+'/assets/images/'+article.image+'-1440.webp':base+'/assets/images/baiwu-1440.webp';
 const ld=article?{'@context':'https://schema.org','@type':article.analysis?'Article':'NewsArticle',headline:article.title,description:article.dek,datePublished:article.date+'T12:00:00+07:00',dateModified:(article.updated||article.modified||article.date)+'T12:00:00+07:00',inLanguage:'ru',articleSection:categories[article.category],author:{'@type':'Organization',name:article.author,url:base+'/about/'},publisher:{'@type':'Organization',name:'TECTONICA',url:base},mainEntityOfPage:canonical,...(article.image?{image:[og]}:{})}:{'@context':'https://schema.org','@type':'WebSite',name:'TECTONICA',url:base,inLanguage:'ru'};
 const html='<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+' — TECTONICA</title><meta name="description" content="'+esc(desc)+'"><meta name="theme-color" content="#f4f2ed"><link rel="canonical" href="'+canonical+'"><meta property="og:type" content="'+(article?'article':'website')+'"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="TECTONICA"><meta property="og:title" content="'+esc(title)+'"><meta property="og:description" content="'+esc(desc)+'"><meta property="og:url" content="'+canonical+'"><meta property="og:image" content="'+og+'"><meta name="twitter:card" content="summary_large_image">'+(options.noindex?'<meta name="robots" content="noindex,follow">':'')+'<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="alternate" type="application/rss+xml" title="TECTONICA" href="/feed.xml"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/assets/editorial.css">'+(article?'<link rel="stylesheet" href="/assets/gallery.css"><link rel="stylesheet" href="/assets/article.css"><script src="/assets/gallery.js" defer></script>':'')+'<script type="application/ld+json">'+json(article?[ld,{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Главная',item:base+'/'},{'@type':'ListItem',position:2,name:catName(article.category),item:base+'/category/'+catKey(article.category)+'/'},{'@type':'ListItem',position:3,name:article.title,item:canonical}]}]:ld)+'</script><script src="/assets/site.js?v=photo23-'+edition+'" defer></script></head><body'+(article?' class="article-page"':'')+'><a class="skip" href="#main">К содержанию</a><header><div class="utility"><span>МИРОВАЯ АРХИТЕКТУРА И ДИЗАЙН</span><span><a href="/archive/">Архив</a><a href="/search/">Поиск <span aria-hidden="true">⌕</span></a></span></div><a class="wordmark" href="/" aria-label="TECTONICA — главная">TECTONICA<span class="logo-dot">•</span></a><div class="strap"><span>Мировая архитектура и дизайн. По-русски.</span><time datetime="'+edition+'">'+dateLabel(edition)+'</time></div><nav aria-label="Рубрики">'+nav+'</nav>'+formats+'</header><main id="main">'+body+'</main><footer><div class="footer-top"><a class="footer-logo" href="/">TECTONICA<span>•</span></a><p>Мир меняется.<br>Смотрим внимательно.</p></div><div class="footer-bottom"><span>Архитектура и дизайн по-русски · © 2026</span><a href="/about/">Об издании и источниках</a><a href="/advertising/">Реклама</a><a href="/archive/">Архив</a><a href="https://t.me/designers_media" aria-label="TECTONICA в Telegram">Telegram ↗</a><a href="https://max.ru/channel_designers_media" aria-label="TECTONICA в MAX">MAX ↗</a><a href="/feed.xml">RSS ↗</a></div></footer></body></html>';
 const file=route==='/404.html'?'404.html':route.slice(1)+'index.html';fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});fs.writeFileSync(path.join(root,file),html);if(!options.noindex)pages.push({route,modified:article?.updated||article?.modified||article?.date||edition});
}
const lead={...byId(editorialRevision.picks[0].id),...(editorialRevision.picks[0].image?{image:editorialRevision.picks[0].image,imageAlt:editorialRevision.picks[0].imageAlt}:{})},secondary=byId(editorialRevision.picks[1].id);
const home='<div class="editionline"><span><i></i> ВЫБОР РЕДАКЦИИ</span><span>'+dateLabel(edition)+'</span></div><section class="opening"><article class="lead"><a href="'+url(lead)+'">'+img(lead,true)+credit(lead)+meta(lead)+'<h1>'+esc(lead.title)+'</h1><p>'+esc(lead.dek)+'</p></a></article><div class="opening-right"><article class="secondary"><a href="'+url(secondary)+'">'+img(secondary)+credit(secondary)+meta(secondary)+'<h2>'+esc(secondary.title)+'</h2><p>'+esc(secondary.dek)+'</p></a></article><a class="editor-pick" href="/daily/"><span>ЕЖЕДНЕВНЫЙ МАРШРУТ ↗</span><h3>Мир дизайна<br>за 15 минут</h3><p>'+esc(selectionLabel)+': что в них важно и на какие детали посмотреть.</p></a></div></section>'+
'<a class="promise" href="/daily/"><strong>15 минут — и вы в курсе.</strong><span>'+esc(selectionLabel)+' с объяснением выбора. Выпуск на '+dateLabel(edition)+'.</span><b aria-hidden="true">↗</b></a>'+
section('01','Выбор редакции','/archive/')+'<section class="grid stories">'+editorialList(['moscow-transport-museum-melnikov-garage-2026','nested-house-iterare-valencia-2026','clinamen-onassis-mandra-athens-2026']).map(a=>photoCard(a)).join('')+'</section>'+
'<section class="splitfeed"><div>'+section('02','Коротко','/feed/','Вся лента')+articles.filter(a=>a.format==='Коротко').slice(-6).map(row).join('')+'</div><aside class="agenda"><span class="eyebrow">СЕНТЯБРЬ / КАЛЕНДАРЬ</span><h2>Стоит увидеть</h2><a href="/articles/open-house/"><b>12–20</b><span>сентября · Лондон</span><h3>Open House</h3></a><a href="/articles/vrubel-ceramics-2026/"><b>18.09</b><span>открытие · Москва</span><h3>Врубель. Керамика</h3></a><a href="/articles/buenos-aires/"><b>22.09</b><span>старт · Буэнос-Айрес</span><h3>Архитектурная биеннале</h3></a></aside></section>'+
section('03','Разобраться','/features/')+'<section class="grid feature-grid">'+longreads.map(a=>photoCard(a)).join('')+'</section>'+
'<section class="radar-band">'+(currentIssue.radar?'<div class="prose"><h2>'+esc(currentIssue.radar.title)+'</h2><h3>'+esc(currentIssue.radar.subtitle)+'</h3><p>'+esc(currentIssue.radar.text)+'</p><a href="/daily/">Выпуск и темы для больших материалов ↗</a></div>':'')+section('04','Radar','/radar/','Все наблюдения')+'<p class="radar-intro">Ранние сигналы и новые подходы. Что заметили — и что ещё предстоит проверить.</p><div class="grid">'+radar.map(a=>photoCard(a)).join('')+'</div></section>'+
section('05','Мебель, свет и предметы','/category/furniture/')+'<section class="grid four">'+editorialList(['chant','wax','gradas','radford']).map(a=>photoCard(a)).join('')+'</section>'+
'<section class="featureband"><div>'+img(byId('malonic'))+'</div><div><span class="eyebrow">ДОМ / МЕКСИКА</span><h2>Двор, который открывает дом к океану</h2><p>Casa Malonic: как HW-STUDIO выстроили путь от улицы к морскому горизонту.</p><a href="/articles/malonic/">Рассмотреть проект ↗</a></div></section>'+
section('06','Люди и события','/category/exhibitions/')+'<section class="grid four">'+editorialList(['medals','reading-room','buenos-aires','materials']).map(a=>photoCard(a)).join('')+'</section>'+
'<div class="archive-call"><h2>Продолжить знакомство.</h2><a href="/archive/">Все '+articles.length+' материалов ↗</a></div>';
write('/','Мировая архитектура, интерьеры и дизайн','За 15 минут — главное в мировой архитектуре и дизайне. Реальные проекты, новые предметы, разборы и ранние тенденции по-русски.',home);
write('/features/','Разборы','Большие редакционные материалы о решениях в архитектуре, интерьерах и дизайне.',heading('Разобраться','Несколько проектов, один важный вопрос. Сравниваем решения и объясняем, что из них полезно для практики.','БОЛЬШИЕ МАТЕРИАЛЫ')+'<section class="grid feature-grid">'+longreads.map(a=>card(a)).join('')+'</section>');
write('/radar/','Radar — ранние тенденции','Новые подходы и ранние сигналы в архитектуре и дизайне.',heading('Radar','Конкретные решения, за которыми следит редакция. Для каждого различаем наблюдение, гипотезу и подтверждённый результат.','НАБЛЮДЕНИЯ РЕДАКЦИИ')+issueClosing+'<section class="grid">'+radar.map(a=>card(a)).join('')+'</section>');
const dailyGroups=editorialRevision.picks.map((pick,i)=>({n:String(i+1).padStart(2,'0'),time:pick.time,title:byId(pick.id).title,ids:[pick.id],reason:pick.reason}));
write('/daily/','Выпуск за '+dateLabel(edition),'Свежие истории с объяснением редакционного выбора.',heading('Выпуск за '+dateLabel(edition),'Архитектура, интерьеры и предметы. Выбор редакции на '+dateLabel(edition)+'. Время ориентировочное, с просмотром фотографий.','РЕДАКТОРСКИЙ ВЫБОР')+'<div class="prose"><p>'+esc(currentIssue.intro||'Свежие истории и причины редакционного выбора.')+'</p></div>'+dailyGroups.map(g=>{const a=byId(g.ids[0]);return section(g.n,g.title,null)+'<section class="daily-story"><a href="'+url(a)+'">'+img(a)+credit(a)+'</a><div class="prose"><p class="eyebrow">'+esc(g.time)+'</p><p>'+esc(g.reason)+'</p><p>'+esc(a.dek)+'</p><a class="read" href="'+url(a)+'">Читать материал ↗</a></div></section>';}).join('')+issueClosing+'<div class="archive-call"><h2>Лента и прошлые выпуски</h2><a href="/feed/">Открыть ленту ↗</a></div>');
for(const a of articles){
 const related=a.related?editorialList(a.related):articles.filter(b=>b.id!==a.id&&catKey(b.category)===catKey(a.category)).slice(0,3);
 const domain=new URL(a.source).hostname.replace('www.','');
 const introCount=a.body[0]?.startsWith('## ')?0:(a.body[1]&&!a.body[1].startsWith('## ')&&(a.body[0].length+a.body[1].length<340)?2:1);
 const intro=a.body.slice(0,introCount).map(p=>'<p>'+esc(p)+'</p>').join('');
 const heroImage=a.image?'<figure class="article-figure">'+img(a,true).replace('70vw','(min-width: 1000px) 50vw, 100vw')+'<figcaption>'+esc(a.credit)+' · <a href="'+esc(a.source)+'" rel="noopener">Источник ↗</a></figcaption></figure>':'';
 const body='<div class="breadcrumbs"><a href="/">Главная</a> / <a href="/category/'+catKey(a.category)+'/">'+catName(a.category)+'</a></div><article class="article"><div class="article-hero">'+heroImage+'<div class="hero-copy"><header class="article-heading"><span class="eyebrow"><a href="/category/'+catKey(a.category)+'/">'+catName(a.category)+'</a> · '+esc(a.place)+'</span><h1>'+esc(a.title)+'</h1><p class="dek">'+esc(a.dek)+'</p><div class="byline"><a href="/about/">'+a.author+'</a><time datetime="'+a.date+'">'+dateLabel(a.date)+'</time>'+(a.updated?'<span>Обновлено '+dateLabel(a.updated)+'</span>':'')+'<span>'+Math.max(1,Math.ceil(a.body.join(' ').split(/\s+/).length/160))+' мин чтения</span></div></header><div class="hero-intro prose">'+intro+'</div></div></div><div class="article-layout"><aside class="project-details"><span class="eyebrow">'+(a.analysis?'АНАЛИЗ РЕДАКЦИИ':'ДЕТАЛИ ПРОЕКТА')+'</span><p>'+esc(a.event)+'</p><a href="/category/'+catKey(a.category)+'/">'+catName(a.category)+' ↗</a></aside><div class="prose article-body">'+articleBody(a,introCount)+(a.correction?'<aside class="sourcebox"><strong>Уточнение · '+dateLabel(a.updated)+'</strong><p>'+esc(a.correction)+'</p></aside>':'')+'<div class="sourcebox"><strong>Источники и подробности</strong>'+sourceLinks(a)+'<p>Редакционное изложение по опубликованным материалам. Даты и статус проекта указаны отдельно от даты публикации TECTONICA.</p></div><div class="share"><button type="button" data-copy>Скопировать ссылку ↗</button><span role="status" data-copy-status></span></div></div></div></article>'+section('ЕЩЁ','По теме','/category/'+catKey(a.category)+'/')+'<section class="grid">'+related.map(b=>card(b)).join('')+'</section>';
 write(url(a),a.title,a.dek,body,a);
}
for(const [k,label] of Object.entries(categories)){const v=catName(k);const group=articles.filter(a=>k==='furniture'?catKey(a.category)===k:a.category===k);write('/category/'+k+'/',v+' — новости и проекты',v+': новые проекты, предметы, события и люди в TECTONICA.','<div class="page-title"><span class="eyebrow">РУБРИКА / '+group.length+' МАТЕРИАЛОВ</span><h1>'+v+'</h1></div><section class="grid">'+group.map(a=>card(a)).join('')+'</section>');}
const dates=[...new Set(articles.map(a=>a.date))].sort().reverse();
const archiveRoute=d=>'/archive/'+d.replaceAll('-','/')+'/';
const datedList=d=>'<div class="archive-date"><a href="'+archiveRoute(d)+'">'+dateLabel(d)+'</a><span>'+articles.filter(a=>a.date===d).length+' материалов</span></div>'+articles.filter(a=>a.date===d).map(row).join('');
write('/archive/','Архив публикаций','Все выпуски и материалы TECTONICA по датам.',heading('Архив','Дата выпуска — день публикации в TECTONICA. Даты завершения проектов и событий указаны в статьях.','ВСЕ ВЫПУСКИ')+dates.map(datedList).join('')+'<div class="archive-call"><h2>Предыдущая версия</h2><a href="/archive/legacy/">Сохранённый выпуск ↗</a></div>');
for(const d of dates)write(archiveRoute(d),'Выпуск от '+dateLabel(d),'Материалы TECTONICA от '+dateLabel(d)+'.',heading('Выпуск от '+dateLabel(d),'Проекты, предметы, люди и редакционные наблюдения.')+datedList(d));
write('/feed/','Короткая лента','Коротко о новых проектах, продуктах, выставках и дизайнерах.',heading('Коротко','Новые проекты, предметы и события. Самое существенное — в нескольких предложениях.',dateLabel(edition))+articles.filter(a=>a.format==='Коротко').map(row).join(''));
write('/search/','Поиск по изданию','Найти материал по теме, проекту, городу или имени.','<div class="page-title"><span class="eyebrow">ПО ВСЕМ МАТЕРИАЛАМ</span><h1>Найти историю</h1></div><form class="searchform" action="/search/"><label for="q">Проект, город, дизайнер или тема</label><div><input id="q" name="q" type="search" placeholder="Например, дерево или Сеул" autocomplete="off"><button>Найти ↗</button></div></form><p id="search-status" role="status">'+articles.length+' материалов</p><div id="search-results">'+articles.map(row).join('')+'</div><noscript><p>Интерактивный поиск требует JavaScript. Все материалы перечислены ниже формы и доступны в архиве.</p></noscript>',null,{noindex:true});
write('/about/','Об издании и источниках','Редакционные принципы TECTONICA: факты, фотографии проектов и источники.','<div class="page-title"><span class="eyebrow">ОБ ИЗДАНИИ</span><h1>Смотрим мир.<br>Пишем по-русски.</h1></div><div class="prose about"><p>TECTONICA — издание о мировой архитектуре, интерьерах и предметном дизайне. Нас интересуют здания, вещи и люди, которые меняют повседневную среду.</p><h2>Наш редакторский выбор</h2><p>Нас интересует конкретное решение: как устроено пространство, работает материал, меняется повседневное использование здания или вещи. Известное имя и эффектная фотография сами по себе не определяют место на главной. В ежедневном маршруте объясняем выбор пяти историй.</p><h2>Как мы выбираем истории</h2><p>Сначала собираем широкий круг кандидатов, затем проверяем факты, даты и источники. Масштаб текста зависит от истории: небольшой запуск может быть короткой заметкой, а архитектурный проект — отдельным материалом.</p><h2>Источники и фотографии</h2><p>У каждого материала есть ссылка на исходную публикацию. Изображения показывают соответствующий проект или заявленную площадку; визуализации обозначены как визуализации. Авторские права на фотографии принадлежат указанным авторам и правообладателям. Если автор не назван в источнике, указываем организацию, предоставившую изображение.</p><h2>Даты и проверка</h2><p>Дата публикации не означает дату завершения здания. Мы разделяем анонс, проект и построенный объект. Оценки редакции отделяем от характеристик, заявленных авторами.</p><h2>Исправления</h2><p>Сообщить о неточности или фотокредите можно через <a href="https://github.com/aszemel23-art/tectonica.media/issues">репозиторий издания ↗</a>, указав страницу и подтверждающий источник.</p><p>Материалы подготовлены редакцией TECTONICA с использованием инструментов ИИ для поиска, обработки и редакционного изложения. Мы не выдаём их за репортажи с места событий.</p></div>');
write('/advertising/','Реклама и партнёрство','Реклама на TECTONICA: публикация от 7 000 рублей, статья под ключ 15 000 рублей, спецпроекты. Архитектура, интерьеры и дизайн.','<link rel="stylesheet" href="/assets/partners.css">'+fs.readFileSync(path.join(root,'content/advertising.inc'),'utf8'));
write('/404.html','Страница не найдена','Вернитесь к свежим историям TECTONICA.','<div class="page-title"><span class="eyebrow">404</span><h1>Здесь пока пусто.</h1><p>Нужная история могла сменить адрес.</p><a class="button" href="/archive/">Найти в архиве ↗</a></div>',null,{noindex:true});
fs.mkdirSync(path.join(root,'editorial'),{recursive:true});
fs.writeFileSync(path.join(root,'editorial',edition+'-candidates.json'),JSON.stringify(candidates,null,2));
fs.writeFileSync(path.join(root,'assets/search.json'),JSON.stringify(articles.map(a=>({title:a.title,dek:a.dek,text:a.body.join(' '),format:a.format,date:a.date,category:catName(a.category),place:a.place,url:url(a)}))));
fs.writeFileSync(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+pages.map(p=>'<url><loc>'+base+p.route+'</loc><lastmod>'+p.modified+'</lastmod></url>').join('')+'</urlset>');
fs.writeFileSync(path.join(root,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: '+base+'/sitemap.xml\n');
fs.writeFileSync(path.join(root,'feed.xml'),'<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>TECTONICA</title><link>'+base+'</link><description>Мировая архитектура и дизайн по-русски</description><language>ru</language>'+articles.map(a=>'<item><title>'+esc(a.title)+'</title><link>'+base+url(a)+'</link><guid>'+base+url(a)+'</guid><pubDate>'+new Date(a.date+'T12:00:00+07:00').toUTCString()+'</pubDate><description>'+esc(a.dek)+'</description></item>').join('')+'</channel></rss>');
fs.writeFileSync(path.join(root,'.nojekyll'),'');
console.log('Built',pages.length,'indexable pages;',articles.length,'articles;',candidates.length,'candidates.');





