import fs from 'node:fs';
import path from 'node:path';
import {articles,categories,edition,candidates} from '../content.mjs';
const root=path.resolve(import.meta.dirname,'..'),base='https://tectonica.media';
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const json=o=>JSON.stringify(o).replaceAll('<','\\u003c');
const url=a=>'/articles/'+a.id+'/';
const nav=Object.entries(categories).map(([k,v])=>'<a href="/category/'+k+'/">'+v+'</a>').join('');
const img=(a,large=false)=>a.image?'<img src="/assets/images/'+a.image+'-'+(large?'1440':'640')+'.webp" srcset="/assets/images/'+a.image+'-640.webp 640w, /assets/images/'+a.image+'-1440.webp 1440w" sizes="'+(large?'(max-width: 700px) 100vw, 70vw':'(max-width: 700px) 100vw, 33vw')+'" width="1440" height="1080" alt="'+esc(a.imageAlt||a.title)+'" '+(large?'fetchpriority="high"':'loading="lazy"')+'>':'';
const meta=a=>'<div class="meta"><span>'+categories[a.category]+'</span><span>'+esc(a.place)+'</span></div>';
const card=(a,cls='')=>'<article class="card '+cls+'"><a href="'+url(a)+'">'+img(a)+(a.illustration?'<span class="illustration-label">Иллюстрация TECTONICA</span>':'')+meta(a)+'<h3>'+esc(a.title)+'</h3><p>'+esc(a.dek)+'</p><span class="read">'+a.format+' ↗</span></a></article>';
const row=a=>'<article class="newsrow"><span class="rowcategory">'+categories[a.category]+'</span><a href="'+url(a)+'">'+(a.illustration?'<span class="row-illustration">'+img(a)+'<small>Иллюстрация</small></span>':'')+'<h3>'+esc(a.title)+'</h3><p>'+esc(a.dek)+'</p></a><span class="arrow">↗</span></article>';
const section=(n,t,link,label='Все материалы')=>'<div class="sectionhead"><span class="sectionnumber">'+n+'</span><h2>'+t+'</h2>'+(link?'<a href="'+link+'">'+label+' ↗</a>':'')+'</div>';
const pages=[];
function write(route,title,desc,body,article,options={}){
 const canonical=base+route; const og=article?.image?base+'/assets/images/'+article.image+'-1440.webp':base+'/assets/images/baiwu-1440.webp';
 const ld=article?{'@context':'https://schema.org','@type':'NewsArticle',headline:article.title,description:article.dek,datePublished:article.date+'T12:00:00+07:00',dateModified:article.date+'T12:00:00+07:00',inLanguage:'ru',articleSection:categories[article.category],author:{'@type':'Organization',name:article.author,url:base+'/about/'},publisher:{'@type':'Organization',name:'TECTONICA',url:base},mainEntityOfPage:canonical,...(article.image?{image:[og]}:{})}:{'@context':'https://schema.org','@type':'WebSite',name:'TECTONICA',url:base,inLanguage:'ru'};
 const html='<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+' — TECTONICA</title><meta name="description" content="'+esc(desc)+'"><meta name="theme-color" content="#f4f2ed"><link rel="canonical" href="'+canonical+'"><meta property="og:type" content="'+(article?'article':'website')+'"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="TECTONICA"><meta property="og:title" content="'+esc(title)+'"><meta property="og:description" content="'+esc(desc)+'"><meta property="og:url" content="'+canonical+'"><meta property="og:image" content="'+og+'"><meta name="twitter:card" content="summary_large_image">'+(options.noindex?'<meta name="robots" content="noindex,follow">':'')+'<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="alternate" type="application/rss+xml" title="TECTONICA" href="/feed.xml"><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">'+json(ld)+'</script><script src="/assets/site.js" defer></script></head><body><a class="skip" href="#main">К содержанию</a><header><div class="utility"><span>МИРОВАЯ АРХИТЕКТУРА И ДИЗАЙН</span><span><a href="/archive/">Архив</a><a href="/search/">Поиск <span aria-hidden="true">⌕</span></a></span></div><a class="wordmark" href="/" aria-label="TECTONICA — главная">TECTONICA<span class="logo-dot">•</span></a><div class="strap"><span>Пространства. Предметы. Люди.</span><time datetime="'+edition+'">14 сентября 2026</time></div><nav aria-label="Рубрики">'+nav+'</nav></header><main id="main">'+body+'</main><footer><div class="footer-top"><a class="footer-logo" href="/">TECTONICA<span>•</span></a><p>Мир меняется.<br>Смотрим внимательно.</p></div><div class="footer-bottom"><span>Архитектура и дизайн по-русски · © 2026</span><a href="/about/">Об издании и источниках</a><a href="/archive/">Архив</a><a href="/feed.xml">RSS ↗</a></div></footer></body></html>';
 const file=route==='/404.html'?'404.html':route.slice(1)+'index.html';fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});fs.writeFileSync(path.join(root,file),html);if(!options.noindex)pages.push(route);
}
const lead=articles[0],secondary=articles[1];
const home='<div class="editionline"><span><i></i> В ФОКУСЕ</span><span>Сентябрь: от Роттердама до Сеула</span></div><section class="opening"><article class="lead"><a href="'+url(lead)+'">'+img(lead,true)+meta(lead)+'<h1>'+esc(lead.title)+'</h1><p>'+esc(lead.dek)+'</p></a></article><div class="opening-right"><article class="secondary"><a href="'+url(secondary)+'">'+img(secondary)+meta(secondary)+'<h2>'+esc(secondary.title)+'</h2><p>'+esc(secondary.dek)+'</p></a></article><a class="editor-pick" href="/articles/materials/"><span>НА ЭТОЙ НЕДЕЛЕ ↗</span><h3>Материалы, с которыми будем строить завтра</h3><p>Material Matters · 15–17 сентября</p></a></div></section>'+
section('01','Новые истории','/archive/')+'<section class="grid stories">'+articles.slice(2,8).map(a=>card(a)).join('')+'</section>'+
'<section class="splitfeed"><div>'+section('02','Коротко','/feed/','Вся лента')+articles.filter(a=>a.format==='Коротко').slice(6,12).map(row).join('')+'</div><aside class="agenda"><span class="eyebrow">КАЛЕНДАРЬ</span><h2>Стоит увидеть</h2><a href="/articles/open-house/"><b>12–20</b><span>сентября · Лондон</span><h3>Open House</h3></a><a href="/articles/materials/"><b>15–17</b><span>сентября · Лондон</span><h3>Material Matters</h3></a><a href="/articles/buenos-aires/"><b>22.09</b><span>старт · Буэнос-Айрес</span><h3>Архитектурная биеннале</h3></a></aside></section>'+
'<section class="featureband"><div>'+img(articles[6])+'</div><div><span class="eyebrow">ПРОСТРАНСТВО / МЕКСИКА</span><h2>Сначала двор.<br>Потом — океан.</h2><p>Как HW-STUDIO выстроили путь от улицы к морскому горизонту.</p><a href="/articles/malonic/">Рассмотреть Casa Malonic ↗</a></div></section>'+
section('03','Материалы и предметы','/category/objects/')+'<section class="grid four">'+['materials','wax','gradas','radford'].map(id=>card(articles.find(a=>a.id===id))).join('')+'</section>'+
section('04','Места и люди','/category/people/')+'<section class="grid four">'+['ceramics','medals','reading-room','buenos-aires'].map(id=>card(articles.find(a=>a.id===id))).join('')+'</section>'+
'<div class="archive-call"><h2>У каждой истории есть продолжение.</h2><a href="/archive/">Все '+articles.length+' материалов выпуска ↗</a></div>';
write('/','Мировая архитектура, интерьеры и дизайн','Ежедневное издание о мировой архитектуре, интерьерах, мебели, свете, материалах и людях. Новости, проекты и выставки.',home);
for(const a of articles){
 const related=articles.filter(b=>b.id!==a.id&&b.category===a.category).slice(0,3);
 const domain=new URL(a.source).hostname.replace('www.','');
 const body='<div class="breadcrumbs"><a href="/">Главная</a> / <a href="/category/'+a.category+'/">'+categories[a.category]+'</a></div><article class="article"><header class="article-heading"><span class="eyebrow">'+a.format+' · '+esc(a.place)+'</span><h1>'+esc(a.title)+'</h1><p class="dek">'+esc(a.dek)+'</p><div class="byline"><a href="/about/">'+a.author+'</a><time datetime="'+a.date+'">14 сентября 2026</time><span>'+Math.max(1,Math.ceil(a.body.join(' ').split(/\s+/).length/160))+' мин чтения</span></div></header>'+(a.image?'<figure class="article-figure">'+img(a,true)+'<figcaption>'+esc(a.credit)+' · <a href="'+esc(a.source)+'" rel="noopener">Источник новости ↗</a></figcaption></figure>':'')+'<div class="article-layout"><aside><span class="eyebrow">ДЕТАЛИ</span><p>'+esc(a.event)+'</p><a href="/category/'+a.category+'/">'+categories[a.category]+' ↗</a></aside><div class="prose">'+a.body.map((p,i)=>'<p>'+esc(p)+'</p>'+(a.id==='johnny'&&i===1?'<figure class="detail-photo"><img src="/assets/images/johnny-detail-1440.webp" alt="Три формы светильников Johnny: подвесная, напольная и настольная" loading="lazy"><figcaption>Johnny · Faye Toogood / London Design Festival</figcaption></figure>':'')).join('')+'<div class="sourcebox"><strong>Источник и подробности</strong><a href="'+esc(a.source)+'" rel="noopener">'+domain+' ↗</a><p>Редакционное изложение по опубликованным материалам. Даты и статус проекта указаны отдельно от даты публикации TECTONICA.</p></div><div class="share"><button type="button" data-copy>Скопировать ссылку ↗</button><span role="status" data-copy-status></span></div></div></div></article>'+section('ЕЩЁ','По теме','/category/'+a.category+'/')+'<section class="grid">'+related.map(b=>card(b)).join('')+'</section>';
 write(url(a),a.title,a.dek,body,a);
}
for(const [k,v] of Object.entries(categories)){const group=articles.filter(a=>a.category===k);write('/category/'+k+'/',v+' — новости и проекты',v+': новые проекты, предметы, события и люди в TECTONICA.','<div class="page-title"><span class="eyebrow">РУБРИКА / '+group.length+' МАТЕРИАЛОВ</span><h1>'+v+'</h1></div><section class="grid">'+group.map(a=>card(a)).join('')+'</section>');}
const archive='<div class="page-title"><span class="eyebrow">ВСЕ ВЫПУСКИ</span><h1>Архив</h1><p>Дата здесь — день публикации в TECTONICA. Даты проектов и событий указаны внутри материалов.</p></div><div class="archive-date"><a href="/archive/2026/09/14/">14 сентября 2026</a><span>'+articles.length+' материалов</span></div>'+articles.map(row).join('')+'<div class="archive-call"><h2>Предыдущая версия издания</h2><a href="/archive/legacy/">Открыть сохранённый выпуск ↗</a></div>';
write('/archive/','Архив публикаций','Все выпуски и материалы TECTONICA по датам.',archive);
write('/archive/2026/09/14/','Выпуск от 14 сентября 2026','Архитектура и дизайн: 25 материалов выпуска TECTONICA от 14 сентября 2026.',archive);
write('/feed/','Короткая лента','Коротко о новых проектах, продуктах, выставках и дизайнерах.','<div class="page-title"><span class="eyebrow">14 СЕНТЯБРЯ 2026</span><h1>Коротко</h1><p>Важные детали и новые имена — без длинного вступления.</p></div>'+articles.filter(a=>a.format==='Коротко').map(row).join(''));
write('/search/','Поиск по изданию','Найти материал по теме, проекту, городу или имени.','<div class="page-title"><span class="eyebrow">ПО ВСЕМ МАТЕРИАЛАМ</span><h1>Найти историю</h1></div><form class="searchform" action="/search/"><label for="q">Проект, город, дизайнер или тема</label><div><input id="q" name="q" type="search" placeholder="Например, дерево или Сеул" autocomplete="off"><button>Найти ↗</button></div></form><p id="search-status" role="status">'+articles.length+' материалов</p><div id="search-results">'+articles.map(row).join('')+'</div><noscript><p>Интерактивный поиск требует JavaScript. Все материалы перечислены ниже формы и доступны в архиве.</p></noscript>',null,{noindex:true});
write('/about/','Об издании и источниках','Редакционные принципы TECTONICA: факты, фотографии проектов и источники.','<div class="page-title"><span class="eyebrow">ОБ ИЗДАНИИ</span><h1>Смотрим мир.<br>Пишем по-русски.</h1></div><div class="prose about"><p>TECTONICA — издание о мировой архитектуре, интерьерах и предметном дизайне. Нас интересуют здания, вещи и люди, которые меняют повседневную среду.</p><h2>Как мы выбираем истории</h2><p>Сначала собираем широкий круг кандидатов, затем проверяем факты, даты и источники. Масштаб текста зависит от истории: небольшой запуск может быть короткой заметкой, а архитектурный проект — отдельным материалом.</p><h2>Источники и фотографии</h2><p>У каждого материала есть ссылка на исходную публикацию. Изображения показывают соответствующий проект или заявленную площадку; визуализации обозначены как визуализации. Авторские права на фотографии принадлежат указанным авторам и правообладателям. Если автор не назван в источнике, указываем организацию, предоставившую изображение.</p><h2>Даты и проверка</h2><p>Дата публикации не означает дату завершения здания. Мы разделяем анонс, проект и построенный объект. Оценки редакции отделяем от характеристик, заявленных авторами.</p><h2>Исправления</h2><p>Сообщить о неточности или фотокредите можно через <a href="https://github.com/aszemel23-art/tectonica.media/issues">репозиторий издания ↗</a>, указав страницу и подтверждающий источник.</p><p>Материалы подготовлены редакцией TECTONICA с использованием инструментов ИИ для поиска, обработки и редакционного изложения. Мы не выдаём их за репортажи с места событий.</p></div>');
write('/404.html','Страница не найдена','Вернитесь к свежим историям TECTONICA.','<div class="page-title"><span class="eyebrow">404</span><h1>Здесь пока пусто.</h1><p>Нужная история могла сменить адрес.</p><a class="button" href="/archive/">Найти в архиве ↗</a></div>',null,{noindex:true});
fs.mkdirSync(path.join(root,'editorial'),{recursive:true});
fs.writeFileSync(path.join(root,'editorial',edition+'-candidates.json'),JSON.stringify(candidates,null,2));
fs.writeFileSync(path.join(root,'assets/search.json'),JSON.stringify(articles.map(a=>({title:a.title,dek:a.dek,text:a.body.join(' '),category:categories[a.category],place:a.place,url:url(a)}))));
fs.writeFileSync(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+pages.map(p=>'<url><loc>'+base+p+'</loc><lastmod>'+edition+'</lastmod></url>').join('')+'</urlset>');
fs.writeFileSync(path.join(root,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: '+base+'/sitemap.xml\n');
fs.writeFileSync(path.join(root,'feed.xml'),'<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>TECTONICA</title><link>'+base+'</link><description>Мировая архитектура и дизайн по-русски</description><language>ru</language>'+articles.map(a=>'<item><title>'+esc(a.title)+'</title><link>'+base+url(a)+'</link><guid>'+base+url(a)+'</guid><pubDate>'+new Date(a.date+'T12:00:00+07:00').toUTCString()+'</pubDate><description>'+esc(a.dek)+'</description></item>').join('')+'</channel></rss>');
fs.writeFileSync(path.join(root,'.nojekyll'),'');
console.log('Built',pages.length,'indexable pages;',articles.length,'articles;',candidates.length,'candidates.');

